logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        jdbc:
          core: TRACE
        transaction:
          interceptor: TRACE
